version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: mimi3-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mimi3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  app:
    build: .
    container_name: mimi3-app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/mimi3
      - OLLAMA_HOST=${OLLAMA_HOST:-http://localhost:11434}
      - DEFAULT_LLM=${DEFAULT_LLM:-llama3:8b}
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: 